apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo=congthanh19/demo-app
    argocd-image-updater.argoproj.io/demo.update-strategy: newest-build
    argocd-image-updater.argoproj.io/demo.allow-tags: regexp:^[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
<<<<<<< HEAD
<<<<<<< HEAD
          image: congthanh19/demo-app:f50615069da9106a074c1e90a98b08caeedfda5b
=======
          image: congthanh19/demo-app:f50615069da9106a074c1e90a98b08caeedfda5b
>>>>>>> c52f9ef3c843d1c9d281ae2c1e1c808800a238e2
=======
          image: congthanh19/demo-app:f50615069da9106a074c1e90a98b08caeedfda5b
>>>>>>> 148e9ee (update file main flow gitops 6)
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources: {}

